# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := libcef_dll_wrapper
DEFS_Default := '-DUSING_CEF_SHARED'

# Flags passed to all source files.
CFLAGS_Default := 

# Flags passed to only C files.
CFLAGS_C_Default := 

# Flags passed to only C++ files.
CFLAGS_CC_Default := 

INCS_Default := -I..

OBJS := $(obj).target/$(TARGET)/../libcef_dll/transfer_util.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/cef_byte_read_handler.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/cef_stream_resource_handler.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/cef_xml_object.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/cef_zip_archive.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/libcef_dll_wrapper.o \
	$(obj).target/$(TARGET)/../libcef_dll/wrapper/libcef_dll_wrapper2.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/app_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/auth_callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/before_download_callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/binary_value_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/browser_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/browser_host_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/browser_process_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/client_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/command_line_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/context_menu_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/context_menu_params_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/cookie_manager_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/cookie_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/domdocument_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/domevent_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/domevent_listener_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/domnode_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/domvisitor_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/dictionary_value_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/display_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/download_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/download_item_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/download_item_callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/focus_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/frame_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/geolocation_callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/geolocation_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/jsdialog_callback_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/jsdialog_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/keyboard_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/life_span_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/list_value_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/load_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/menu_model_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/post_data_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/post_data_element_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/process_message_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/proxy_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/read_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/render_process_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/request_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/request_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/resource_bundle_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/resource_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/response_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/scheme_handler_factory_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/scheme_registrar_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/stream_reader_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/stream_writer_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/string_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/task_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/urlrequest_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/urlrequest_client_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/v8accessor_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/v8context_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/v8exception_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/v8handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/v8value_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/web_plugin_info_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/web_plugin_info_visitor_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/cpptoc/write_handler_cpptoc.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/xml_reader_ctocpp.o \
	$(obj).target/$(TARGET)/../libcef_dll/ctocpp/zip_reader_ctocpp.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE)) $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cpp FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Default := 

LIBS := 

$(obj).target/../libcef_dll_wrapper.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/../libcef_dll_wrapper.a: LIBS := $(LIBS)
$(obj).target/../libcef_dll_wrapper.a: TOOLSET := $(TOOLSET)
$(obj).target/../libcef_dll_wrapper.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink)

all_deps += $(obj).target/../libcef_dll_wrapper.a
# Add target alias
.PHONY: libcef_dll_wrapper
libcef_dll_wrapper: $(obj).target/../libcef_dll_wrapper.a

# Add target alias to "all" target.
.PHONY: all
all: libcef_dll_wrapper

